// <auto-generated />
using System;
using AirTracker_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirTracker_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AirTracker_API.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AirTracker_API.Models.RobotEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HardwareToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastKnownIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Robots");
                });

            modelBuilder.Entity("AirTracker_API.Models.SessionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RobotId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VideoFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RobotId");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AirTracker_API.Models.SessionEntity", b =>
                {
                    b.HasOne("AirTracker_API.Models.RobotEntity", "Robot")
                        .WithMany("Sessions")
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirTracker_API.Models.ApplicationUser", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AirTracker_API.Models.TelemetryDocument", "TelemetryData", b1 =>
                        {
                            b1.Property<int>("SessionEntityId");

                            b1.HasKey("SessionEntityId");

                            b1.ToTable("Sessions");

                            b1
                                .ToJson("TelemetryData")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("SessionEntityId");

                            b1.OwnsMany("AirTracker_API.Models.DataPoint", "DataPoints", b2 =>
                                {
                                    b2.Property<int>("TelemetryDocumentSessionEntityId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<double>("Angle");

                                    b2.Property<string>("Command")
                                        .IsRequired();

                                    b2.Property<double>("Speed");

                                    b2.Property<long>("TimeOffsetMs");

                                    b2.Property<double>("X");

                                    b2.Property<double>("Y");

                                    b2.HasKey("TelemetryDocumentSessionEntityId", "__synthesizedOrdinal");

                                    b2.ToTable("Sessions");

                                    b2.WithOwner()
                                        .HasForeignKey("TelemetryDocumentSessionEntityId");

                                    b2.OwnsOne("AirTracker_API.Models.SensorData", "Sensors", b3 =>
                                        {
                                            b3.Property<int>("DataPointTelemetryDocumentSessionEntityId");

                                            b3.Property<int>("DataPoint__synthesizedOrdinal");

                                            b3.HasKey("DataPointTelemetryDocumentSessionEntityId", "DataPoint__synthesizedOrdinal");

                                            b3.ToTable("Sessions");

                                            b3.WithOwner()
                                                .HasForeignKey("DataPointTelemetryDocumentSessionEntityId", "DataPoint__synthesizedOrdinal");

                                            b3.OwnsOne("AirTracker_API.Models.GasesData", "Gases", b4 =>
                                                {
                                                    b4.Property<int>("SensorDataDataPointTelemetryDocumentSessionEntityId");

                                                    b4.Property<int>("SensorDataDataPoint__synthesizedOrdinal");

                                                    b4.HasKey("SensorDataDataPointTelemetryDocumentSessionEntityId", "SensorDataDataPoint__synthesizedOrdinal");

                                                    b4.ToTable("Sessions");

                                                    b4.WithOwner()
                                                        .HasForeignKey("SensorDataDataPointTelemetryDocumentSessionEntityId", "SensorDataDataPoint__synthesizedOrdinal");

                                                    b4.OwnsOne("AirTracker_API.Models.Mq135Data", "Mq135", b5 =>
                                                        {
                                                            b5.Property<int>("GasesDataSensorDataDataPointTelemetryDocumentSessionEntityId");

                                                            b5.Property<int>("GasesDataSensorDataDataPoint__synthesizedOrdinal");

                                                            b5.Property<double>("Alcohol");

                                                            b5.Property<double>("Co");

                                                            b5.Property<double>("Co2");

                                                            b5.Property<double>("Nh3");

                                                            b5.Property<double>("Voltage");

                                                            b5.HasKey("GasesDataSensorDataDataPointTelemetryDocumentSessionEntityId", "GasesDataSensorDataDataPoint__synthesizedOrdinal");

                                                            b5.ToTable("Sessions");

                                                            b5.WithOwner()
                                                                .HasForeignKey("GasesDataSensorDataDataPointTelemetryDocumentSessionEntityId", "GasesDataSensorDataDataPoint__synthesizedOrdinal");
                                                        });

                                                    b4.OwnsOne("AirTracker_API.Models.Mq4Data", "Mq4", b5 =>
                                                        {
                                                            b5.Property<int>("GasesDataSensorDataDataPointTelemetryDocumentSessionEntityId");

                                                            b5.Property<int>("GasesDataSensorDataDataPoint__synthesizedOrdinal");

                                                            b5.Property<double>("Ch4");

                                                            b5.Property<double>("Voltage");

                                                            b5.HasKey("GasesDataSensorDataDataPointTelemetryDocumentSessionEntityId", "GasesDataSensorDataDataPoint__synthesizedOrdinal");

                                                            b5.ToTable("Sessions");

                                                            b5.WithOwner()
                                                                .HasForeignKey("GasesDataSensorDataDataPointTelemetryDocumentSessionEntityId", "GasesDataSensorDataDataPoint__synthesizedOrdinal");
                                                        });

                                                    b4.Navigation("Mq135")
                                                        .IsRequired();

                                                    b4.Navigation("Mq4")
                                                        .IsRequired();
                                                });

                                            b3.OwnsOne("AirTracker_API.Models.ImuData", "Imu", b4 =>
                                                {
                                                    b4.Property<int>("SensorDataDataPointTelemetryDocumentSessionEntityId");

                                                    b4.Property<int>("SensorDataDataPoint__synthesizedOrdinal");

                                                    b4.Property<double>("AccelX");

                                                    b4.Property<double>("AccelY");

                                                    b4.Property<double>("GyroZ");

                                                    b4.HasKey("SensorDataDataPointTelemetryDocumentSessionEntityId", "SensorDataDataPoint__synthesizedOrdinal");

                                                    b4.ToTable("Sessions");

                                                    b4.WithOwner()
                                                        .HasForeignKey("SensorDataDataPointTelemetryDocumentSessionEntityId", "SensorDataDataPoint__synthesizedOrdinal");
                                                });

                                            b3.Navigation("Gases")
                                                .IsRequired();

                                            b3.Navigation("Imu")
                                                .IsRequired();
                                        });

                                    b2.Navigation("Sensors")
                                        .IsRequired();
                                });

                            b1.Navigation("DataPoints");
                        });

                    b.Navigation("Robot");

                    b.Navigation("TelemetryData")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AirTracker_API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AirTracker_API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirTracker_API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AirTracker_API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirTracker_API.Models.ApplicationUser", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("AirTracker_API.Models.RobotEntity", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
